version: 2.0
jobs:
  build:
    docker:
      - image: apertium/base:release
    steps:
      - checkout

      - run: ./autogen.sh
      - run: make

      - run:
          name: Install apertium-quality and awscli
          command: |
            apt-get -y install python3 python3-setuptools python3-dev python3-yaml curl python-pip
            git clone https://github.com/apertium/apertium-quality.git
            cd apertium-quality/mwtools/python3
            python3 ./setup.py install
            cd ../../
            ./autogen.sh && make && make install
            cd ../../../
            pip install awscli

      - run:
          name: Measure coverage
          command: |
            mkdir /tmp/res/
            curl https://raw.githubusercontent.com/taruen/apertiumpp/master/data4apertium/corpora/jam/uzb.txt > /tmp/jam.uzb.txt
            sh cov.sh jam
            curl https://raw.githubusercontent.com/taruen/apertiumpp/master/data4apertium/corpora/udhr/udhr_uzb.txt > /tmp/udhr.uzb.txt
            sh cov.sh udhr
            curl https://raw.githubusercontent.com/taruen/apertiumpp/master/data4apertium/corpora/bible/uzb.nt.ibt.txt > /tmp/bible.uzb.txt
            sh cov.sh bible
            aws s3 cp /tmp/res/ s3://apertium/apertium-uzb/ --exclude "*" --include "cov.*.txt"
            aws s3 cp /tmp/res/ s3://apertium/apertium-uzb/ --exclude "*" --include "cov.*.svg"

      - store_artifacts:
          path: /tmp/res/